version: "3.9"

services:
  flask_app:
    container_name: flask_app
    image: pythonapi:1.0.0
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - "4000:4000"
    environment:
      - DB_URL=postgresql://home:1234@localhost:5432/postgres
    # depends_on:
    #   - flask_db
  # flask_db:
  #   container_name: flask_db
  #   image: postgres:12
  #   ports:
  #   - "5434:5432"
  #   environment:
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_DB=postgres
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data

# volumes:
#   pgdata: {}
  